export const codeToImage = (code: number | undefined) => {
  if (code === 1000) return "images/sunny.svg";
  else if (code === 1003) return "images/sunny intervals.svg";
  else if (code === 1006) return "images/cloudy.svg";
  else if (code === 1009) return "images/cloudy.svg";
  else if (code === 1030) return "images/mist.svg";
  else if (code === 1063) return "images/patchy rain.svg";
  else if (code === 1066) return "images/patchy snow.svg";
  else if (code === 1069) return "images/patchy sleet.svg";
  else if (code === 1072) return "images/freezing drizzle.svg";
  else if (code === 1087) return "images/thundery.svg";
  else if (code === 1114) return "images/blowing snow.svg";
  else if (code === 1117) return "images/blizzard.svg";
  else if (code === 1135) return "images/mist.svg";
  else if (code === 1147) return "images/mist.svg";
  else if (code === 1150) return "images/patchy rain.svg";
  else if (code === 1168) return "images/freezing drizzle.svg";
  else if (code === 1171) return "images/freezing drizzle.svg";
  else if (code === 1180) return "images/patchy rain.svg";
  else if (code === 1183) return "images/patchy rain.svg";
  else if (code === 1186) return "images/moderate rain.svg";
  else if (code === 1189) return "images/moderate rain.svg";
  else if (code === 1192) return "images/heavy rain.svg";
  else if (code === 1195) return "images/heavy rain.svg";
  else if (code === 1198) return "images/freezing drizzle.svg";
  else if (code === 1201) return "images/freezing drizzle.svg";
  else if (code === 1204) return "images/patchy sleet.svg";
  else if (code === 1207) return "images/patchy sleet.svg";
  else if (code === 1210) return "images/patchy snow.svg";
  else if (code === 1216) return "images/moderate snow.svg";
  else if (code === 1219) return "images/moderate snow.svg";
  else if (code === 1222) return "images/heavy snow.svg";
  else if (code === 1225) return "images/heavy snow.svg";
  else if (code === 1237) return "images/ice pellets.svg";
  else if (code === 1240) return "images/rain shower.svg";
  else if (code === 1243) return "images/rain shower.svg";
  else if (code === 1246) return "images/heavy rain.svg";
  else if (code === 1249) return "images/patchy sleet.svg";
  else if (code === 1252) return "images/patchy sleet.svg";
  else if (code === 1255) return "images/patchy snow.svg";
  else if (code === 1258) return "images/moderate snow.svg";
  else if (code === 1261) return "images/ice pellets.svg";
  else if (code === 1264) return "images/ice pellets.svg";
  else if (code === 1273) return "images/light thunder.svg";
  else if (code === 1276) return "images/heavy thunder.svg";
  else if (code === 1279) return "images/light snow.svg";
  else if (code === 1282) return "images/heavy snow.svg";
  else return "images/sunny intervals.svg";
};
